<?php

?>
<pre style = "font-family:Courier; " >
mmmmmmmmmmmmddddhhhhhhdddddddddddmmmNNmmmmmmmmmmmddddhhyyhhhhhhhdddddddhhhhhhhhhhyyssssyyyyyhhhhyyyssssoosssssoooooosssssssoo+++++++oossyyhhhhhhhhhhyyyssoooossssssosoooosssyyssssssssshhhhyyhhdmmNNNNNN
mmmmmmmmmmmmddddhhhhhddmmmmddddddmmmmNmmmmmmmmmmmmdddhhhyhhhhhhhhddddddhhhhhyyyhhhhhdddhhhyyssssooossoooo++++oooooooossssssoo++++++ooossyyhhhhhhhhyyyyysssooossssssssoooosssyyssssssssyyhhyyyhdmmNNNNNNN
dmmmmmmmmmmmdddddhhhhhddddddddddddmmmNmmmmmmNNNmmmmdddhhyyhhhhhhhhdddddhhhhhhhhhhhhhhyyyssssooooooooo++++++++ooooooooooosssooo+++++ooossyyyhhhhhhyyyyyyssssoossssssssoooosssysssssssssyyyyyyhddmmNNNmNNN
dmmmmmmmmmmmmddddhhhhhhddmmdddddddmmmNNmmmmNNNNNmmmdddhhyyyhhyyyyyhhhhhyyyyyyyyyyyyyyyyyssssssooooooo++++++++++oooooooooooooooo++++oooosyyyhhhhhyyyyyyyssssosssssssosoooosssyssssssssyyyyyyhdddddmmmmNNN
mmmmmmmmmmmmmmddddhhhhhddmmmdddddddmmmNNmmNNNNNNmmmmddhhyyyhhyyyyyyysssssssyyysssssssssssoooosssooooooo++++++++++++++oooooooooooooooooossyyhhhhhhyyyyyyssssssssssssosoooosssyssssssssyyyyhhdddddddmmNNNN
mmmmmmmmmmmmmdddddhhhhhhddmddddddddmmmmmmmNNNNNNNmmmdddhhyyyyyyysssssyyyyssssssyyyssssssssssssysssoooooooooooo+++++++++oooossssssssooooosyyyhhhyyyyyyyysssssssssssssssooosssssssssssyyhhhdddmddddmmNNNNN
dmmmmmmmmmmmmddddddhhhhhhdddddhdddddmmmmmNNmmNNNNmmmddhhyyyyyyyyyyyyyyyyssyyyyyyyyyyyyyssssssssssssooooooooooooooooooossssssssssssssssooossyyyhhyyyyyyyysssosssssssssoooosssyyssssssyhhddmmmmdddmmmmmmmN
dmmmmmmmmmmmmddddddhhhhhhhhhhhhhddddmmmmmNNNNmmmmmmddhyyyyyyyyyyyyyyssoossssssyyyyyyyyyssssssssooo++oooooooosssssssyyyyyyyssyyyyyssssssssooosssyyyyyyyyysssosssssssoooooosssssssssssyyhddmmmmmmmmmmddhdm
ddddmmmmmmmmmdddddddhhhhhhhhhhhhdddddmmmmmNNmmmmmmdhysssyyyyyyyyysoo+++++ooooooosssssssssssooooo+++++++ooooooooosssssssssssssssssyyyyssssssoooossssyyyyysssoooossoooooooosssssssssssyyhdmmmmmmmmmmmdhyhd
dmdddmmmmmmmddddddddhhhhhhhhhhhdddddddmmmmmNmmmmddhysssyyyyyysoo++++//////++++++++++++++oooo++++ooooooo+++++++++oooooooooooossssssssssyyyyyssoossssssyyysssoooososssooooosssssssssssyyhdmmmmmmmmmmdhhhdm
dddddhhhhhddddddddddhhhhhhhhhdddddddddmmmmmmmddhyysssssyysssoo++++////////////::::://///////////////+/////////+++++++++++ooooooooosooosssyyyyysssssssssssssooooooosssoooosssssssosssyyhddmmmmmmmmmddddmm
hyyysssssyhddddddddddhhhhhhhhhhddddddddmmmmddysssssssssssooo+++++/////////::::::::::::::::------:---:::--::::://////////++++++++oooooooooossyyyssysssssssssooooooosssoooosssssssosssyyhddddddmmmmmmdmmNN
ssooooooosyhddddddddddhhhhhhhhhhhhhhdddmmmdysossssssssooo++++++/////////:::::::::::::::-----------------------:::::::::////+++++++++++++++ooossysssssssssssoooooooooooooossssssssssyyhdmddhhhdddddddmmNN
+++++ooosyhdddddddddddhhhyyyyyyyyhhhhddddysooosssooooo+++++++////////:::::::::::::::::::----------------------------::::::://///////////+++++oossssssossssssooooooooooooossssssssyyhhdmmdhyyhhdddddddmmm
++ooossyyhddmmmdddddddhhhyysssoosyyhhhhyyoooooooooo++++++++////////////::///:::::::::--:---------------------::-:::::::::::::/:////////////++++ooosssooosssoooooooooooooossssyyyyyyhhdddhyyyyhhddddddddm
osssyyhhdddmmmmmmdddddhhhyyssooossyhhhysoo++oooo++++++++///////////:::::::::::::::::--::--------------------:--::::::::::::::::::://////////++++++oossooooooooooooooooooosssyyhhhyyyhhhhyyyyyhhddddddddd
yyyyyyhhdddmmmmmmddddddhhyyyssssyyhhyso++/+++oo+/++++++//////////:::::::::::::::::::::::::::---------------::::----:::::::::::::::://////////+++++++ooooooooooooooooooooossyyhhdhhyyhhhyyyyyyyhhdddddddh
hhhyyyyhhdddmmmmmmdddddhhhyyyyhhhhhyso++//++++++++++++//////////:::::::::::::::-::::::::--::-----------------::-:::-::::::::::::::::::::///////+++++++ooooooooooooooooooosyyhhdddhhhhhhyyyyyyyyhdhhhhhhh
hhhhyyhhhddmmmmmmmmmddddhhhyyhhhhyyoo++//+oo+++/++++///////////::::::::::::::::::::---::-------------------------:::::::::::::::::::::::::////++++++++++oooooooosssssooosyyhdddddddhhhhyyyyyyyyhhhhyyyyy
hhhhhhhdddmmmmmmmmmmmmdddhhhyyhhyso+++/++oo+++++++++/////////:::/:::::::::::::::::------------------------------::::::::---:::::::::::::://////++++++++++oooooosssssooossyhddddddhhhhhhyyyyyyyhhdhhyyyyy
ddddddmmmmmmmmmmmmmmmmmdddhhhyyso+++++++oo+++++++++///////////:::::::::::::::::::--------------------------------::::-:-------::::::::::::////////++++oo++ooo+ooooooooosyhdddmdddhhhhhyyyyyyyyyhhhhyyyyy
ddmmmmmNNNNNmmmmmmmmmmmmdddhhhyo++++/++ooo+++//+++///////////:::::::::::::::---:----------------------------------:::-----------::::::::::////////+++ooo+++ooo++oooooosyhdddmmmdhyyyyyyyyyyyyyyyhhhyyyyy
mmmmmNNNNNNNmmmmmmmmmmmmmddddys++++//+ooo+++///+//////////////:::::::::-------------------.............---....-------------------:::::::::://///+++++oooo++oooo++ossssyhddddmmmmdhyyyyyyyyyyyyyyhhhyyyyy
mmmNNNNNNNNNNmmmmmmmmmmmmmmmdyo+/////+oo++++//////////////////:::::::::---------------------.---..--..----.....------------------:::::::::::////+++++++++ooooooo+osyyhhddmmmmmmmddhhhhhhhhhhhhhhhhhhhhhh
NNNNmNmmmmmmNNNNNNNNNNNNNmmmy+/+//::/+o+++++//++////////////::::::::----------------.....---...........--......------------------:::::::::::///////++++ooo+++ooooooshmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmm
NNNmmmNNmmmmNNNNNNNNNNNNNmmhs//+/:::+o++++///++++////////////:::::::-------------..................................----------------::::::://///////++++++oo+ooooooooydddddmmmmNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNmNNmhs+///:::/+++++///////////////////::::::::::--------....................................--.....--------::::::::::////////++++++oooooooooooshmmdmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNdso+//////++++++/////////+////:////:::::::::-----------.........................................---------:::::::::///////++++o+++ooooooooosoydmdmmmNNmmmNNNNNNNNNNNNNNNNNNNNNNN
MMMMNNNNNNNNMMMMMMNNNNNNmho+++//++/++++++///+++///+/////::/::::::::::----------............````...................-......----------::::::::///////+++++o++oooooooooooshdmmmmNmmmmNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMmyo+++++++/++++++////////////////:::::::::::::-------..........................--.........-......----------::::::::///////++++++o+ooooooooooooydmmmmNmmmNNNMMMMMMMMMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMNds++++++++++++++++///+//////////:::::::::::----------........................--------...........------------:::::::::://///+++++oo+oooooooooooshmmmmmmmmNNNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNho++++oo+++++//++///++///+/////::::::::::::----------......................-------------........-------------:::::::::///////++++oooosoooooosooydmmNNmmmmNNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMmyooo+ooo+++o+/////+///++++/////::::::::::::-----------........................---......-..--....------------::::::::::///////+++ooooossssooosooshmmNNmmmmNNMMMMMMMMMMMMMMMMMMMMN
MMMMMMMMMMMMMMMMMMMMMMMdsooooooo++oo+//++++++/++///////::::::::::::-------------......................................--------------::::::::::://////++ooooossssssoosssshmNmmmmmmNNMMMMMMMMMMMMMMMMMMMNN
MMMMMMMMMMMMMMMMMMMMNNNhoooooooooooo++++++++++/////////::::::::::::::----------.........-.-............................--------------:::::::::://///+++ooooosssssssosysshmNNNmmmmmNNMMMMMMMMMMMMMMMMMNNm
MMMMMMMMMMMMMMMMMMMMMNNhooossooooooo++++++++///////////::::::::::::::-------..-..........---------......--...............-----------::::::::::::////++++ooosssyyssssyyysydNNNNNNmmmNNMMMMMMMMMMMMMMMNNmm
MMMMMMMMMMMMMMMMMMMMMMmyooossoooooooo+++++++///////////:::::::::::::--------.---...........-----------------..........-------------:::::::::::://///+++oooosssyyssssyyysydmNMNMNNNNNNMMMMMMMMMMMMMMNNNmm
MMMMMMMMMMMMMMMMMMMMMNdssssssssssooooooooo+++++/////////:::::::::---------------..--.........----------..-..........----------------:::::::::://////+++ooosssyyyssssyyyyyhmMMNMMMNNMMMMMMMMMMMMMMMMMNNmd
NMMMMMMMMMMMMMMMMMMMMNhssssssssssoooooooooo++/+/////////:::::::::---------------------.........------...............-----------------::::::::://////+++ooossssyyssssyyyyyydNMNMMMMMMMMMMMMMMMMMMMMMNNNmd
mNMMMMMMMMMMNNNNNNNNNmhssssssssssooosssoooo++++////////::::::::::------------------------.......-..-..-.......-....-----------:::::----::::::://////++oooossssyyysssyyyyyyhmNNMMMMMMMMMMMMMMMMMMMMMNNNmd
dNNNNMMNNNNNNNNNNNNNNdysssssyyysssssssso++oo++++///////::::::::::::-------------------:---------------------.-----------:---::::---:::::::/::::////++++ooossssyyysssyyyyyyyhdmNNNMMMMMMMMMMMMMMMMMMNNNmm
hmmNNNNNmmmmmmmmmmmmmhssssyyyyysssssssoo++oo++++///////:::::::::::::-------::::::::::::::::--------------------:----::::::::::::::::::::///////////++++ooosssssyyyssyyyyyyyyyhdmNMMMMMMMMMMMMMMMMMMMNNNm
yhddmddddddddddmmmddhyssyyyyyyysssssssoo++oooo+++++////::::::/::::::::::::::::::::::::::::::::----------------:::::::::::::::::::::////////////////+++oooosssssyyyssyyyyyyhyyyhmNMMMMMMMMMMMMMMNNNMMNNNm
syhdddddddddddddhhyyyssssyyyyyysssssssoo++oooo++++++////////////////////////////////:::::::::::::::---:::----::::::::://////+////////++/////++++++++++ooossssssyyyyyyyyyyyhhyyhdmNNNNNNNNNNNNNNNNNNNNNNm
syhdmmmmddhhhyyysssoossysssyyyysssssssoo++ooo+++++++////////++++//////++////++++++++//////::::::/:::::::::-::::::::://+++o+ooo+++++++oo+++++ooo+++ooo+oossooossyyyyyyyyysyhhyyhdmmmmmmmmmmmmmmNNNNNNNNmm
osyhddddhyssoooooo+oosyyyyyyyysssssyssoo+++++++++++++//++++++++++++++oo+++++oossssooo+++////:::::::---::::::::::://++ooosssssssoooooossssooooooooooooooosoooossyyhhhyyyyyyyyyyyhdddddddmmmmmmmmmmmmmmmmm
oossyhhhyso+++++++++++osssyyyysosssyysoo+++++++++++++++ooo+++++++ooooosoossssssyssssooo+++////:::::-------::::://++oossssssooooooooooossssssssssssssssosssooossyyhhhyyyyyyysssyhhhhhddmmmmmmmmmmmmmmmmmm
ooosyyhhyso++++++ooo+++ossssssoossssssooo+++++++++++++ooo+++++++oooooosossssssssoooooooo++++/////:::----::::///++oossoooooooooo+oooo+++/++ooosssssssssoossooossyhhhhyyhyyyyysssyyyyyyhdmNNNNmmmmmmmmmmmm
oooosyhhhyso++++oosssooosssoooossssssoooo+++++++++++++++++++++oossyyyhhhhhhhyyyyyyso++ooo+++///::::-------::://+oooooooosyyssyyyyyhhhysso++++oooosssssooooooossyhyyyyhhhyyyyssssssossydmNNNmmmmmmmmmmmmm
sooossyhhysoo+++++oosssssssooossssyssoo++++o+++++++++/////++osyyyyyyhhhy++yyssoosssyssoooo++//::::--------::://+oooossssoooosyys++yhhysssyssssooooooooo++oooossyyyyyyhhhyyyssssssoossydmmNmmmmmmmmmmmmmm
soooosyyhhysoo++++++ooosossooosssyyyssoo++++++++////+++//+osyyyyso+syyhhyhhsso//oosooosssooo+//:::---------:://+oossoo+oo+//+sshhddysso/+syyyyysooooo++++ooooosyyyyyhhhyyysssssssoossydmmmmmmmmmmmmmmmmm
ysoooosyhhysso+///++++++osssssssyyyyssoo++++++++/////+++++oossss+//+sssyhhyso/--/++o+++++oooo+//:::---.---:::/+ooo+//++++/--/osshhysso+//+ossyyssoooo++++ooooosyyyyyhhhyyyssssssooossydmmmmmmmmmmmmmmmmm
hyoo+ossyhhyso/////+o++/+ossssssyyyyssoo+++++++///////++++ooooo+////++ooooo++::://::/++/::/+++///:::-----:::/+oo+/:/++/////::/+++oooo+////+osssoosoo++//++oooossyyyyyhhyyyssoosoooossydmmmmmmddhhhddmmmm
hysoo+osyyhhyo/:///+o+//:/+ossooyyyysoo++++++++//////++++++/++///://::/:/:::::::////://::::/+++//:::------::/+++/:::::::::/::://:////////+++ooooooo+++++++ooooosyyyyyyyyysoooosssoossyhmmmmmmdyyyyyhdmmm
dhyoo+oosyhhys/:::/+++//::/ossoosyyyso+++++++++/////:://////////:::::::::::::::///////:::-:///////::------://+++/::::://////:::::://::://+++++++++++////++++ooossyyyyyyysooooossssossydmmmmmdhysssyyddmm
mdhsoooossyhhs+//:/+++//::/++ssoossysoo++++++////::::::://////::///::::::::://////////:::::///////::------::/+++//::////////////////////+++++/+++/////////++oosssyyyyyyyso+ooosssooosyhmmmmddhysssyyhdmm
mmdyso++ossyhyo/::/++//::::/+syysyyssooo++++++//:::::--:://///////::::::::://///////:::::::::::///:::-----::/+//////////////////////::///////+++++//::///++oosssyyyysssso+oooosooooosyhmmmmdhhyyyyyhdddm
mmmhyoo+oossyys/:///++/::::/+osssysssoooo+++++///::::--::::::///////::::::::////:::::::::::::::://:::-----://+//:::::::::///////////////////++++///:/:///+++ossyyyyssssoo+osoooooooosyhmmmmddhhhhhddddmm
mmmdhso+++oosys+:://++/:::/++oooosssooooo++++++/::::::::--:://////////////////:::::---:::::::::///::------://+//::::::--:::::///////////////++//::::::///++oossyyyyysooo+ooooooooooosyhdmmmdhhhyyhhhddmm
dmmddyso+++oosyo/::/++/::///+o+//+osooooooo++++//:::::---------::::::::::::::---------:::::::::///::------:://///::::::-------:::////////////::::::::://+++oossyyyysoooooooooooooooosyhdmmmdhhyyyyyhhddm
dddmdhyoo++oosys+/:/+/::://///+/:/+oosoooooo++////:::::------------------------..----::::::::://///::------://///::::::::------------:::::::::::::::////+++oosyyyyyso+oooooooooooooosyhdmmmddhhyyyyhhddd
ddddmdyso+++oosys+:/+/:-://////+/:/ossoooooo++//////:::::------------.-.-.----....---:::::::::////::--.----::////::/::::--------------------:::::///////++ooosyyyyysooosoooooooooooosyhdmmmdddhhhyyhhddd
ddddmdhyso++oosyyo//++/:://////++//+osoooooo++//////::::::--------...............----::::::://///:::------::://///::::::--------------------::::////////++oossyyhyssossssooooooooooosyhdmmmddhhyyyyyhddd
dddddddhyo+++osyyyo//++////////+o+/+osssooooo+//////::::::--------.......-..---------:::::://////:::------:::///++///:::---------....-------::::///////+++oosyyyyyssssssssooooooooossyhdmmmdhhyyyyyyhddd
mdddddddyso++oosyhyo///++/:////+oo++osssooooo+///////:::::::------.......-..----------:::://////:::--------::://++////::---------....------::::://///+++++ossyyysssssssssoooooooooossyhdmmddhhyyyyyhhddd
mmddddddhyso++osyyyyo///+////::///++osssooooo+///////::::::::-----.......-....------::::///////::::--------::::/++/////:::---------------::::::://///+++oooosyyyooososyysoooooooooossyhdddddhhyyyyyhhddd
mmdddddddhso+++osyyhyo+///++/:::::/+ossoooooo++++/////:::::::------........------:::///:://////:::--......-::::/++///////::::-----------::::::::////+++ooooosyyssossshhysooooooooooosyhdddddhhyyyyyyhddd
mmmdddddddyso++ossyyyso+///++//::///+osoooooo++++/////::::::::---------------:::::////::////////:::-------::://++++////////:::::::----:::::::::////+++ooooooyyyssssyhddhsooooooooooosyhdddddhyyyyyyyhddd
dmmdddddddhyoo++ossyyysoo+/++//////:+osoooooo+++++/////:::::::::--------::::://///////////////////::::/::://++ooo+++//++//////::::::::::::::://////+++ooooosyyysssyhdmdyssoooooooooosyhdddddhyyyyyyyhhdd
hdmmdddddddhso++oosyyyysoo++//////::/oooooooo++++++++/////:::::::::::::::////+++//++//////++ooo++////////+++oosssooo++o+/////////::::::::::///////+++oooooosyyysssyhdmdhssoooooooooosyhdddddhyyyyyyyhhdd
hdmmmdddddddyso++oosyyysooo+++///:--/osoooooo++++++++++//////:::::::::///+++o++//:/+o+++osyyhdhyso+++++++oosyhhdhhyssso+/////++++////://///////++++ooossooosyyysssyhdmdhssooooooooossyhdddddhyyyyyyyhhdd
yhdmmdddddddhyoo++ossyyysoo++++//:::+osoooooo+++++++++++++////////////++++++///::::/osssyyhhhhhyyysooooooosyhhhdhhyyyso+/:::://+++++/////////++++ooosssoooosyyssssyhdddhssoooooooooosyhddddhhyyysyyyhhdd
syddmmdddddmdhso+++osyyyyso++++////+ooooooooo++++++++++++++//////+++++++++//::::::::/ossssssoossssssssssyyyyyyyyysssoo+/:::::://+++oo+++++++++++ooossooooossyyssssyydddhssooooooooossyhddddhhyysssyyhhdd
oshdmmdddddmmdys++++osyhysso++++++++oosooooooo+++++++++++++//++++oooo++////:::::::::::/+///////++osyyyhyyyyssssoo+++//::::::://///++ooooo+++++++ooosooooossyyyyysssyhddhysoooooooooosyhddddhhyyyyyyyhhdd
+oyhdmmdddddddhyo+++osyhhyso++//////+osoooooo++++++++++++///+++oo+++/////:::::::::::::///////////+oossysssoo+++++//+/::-::/::///++//++oooo++++++oooooooosssyyyyysssyhdddhyyssssssoossyhdddddhhhhyyhhhhdd
+osyddmmdddddddhs++++osyhyyso+//////+ooooooooo++++///++++////++/////////:::::::///://:://////++//++++++++/////////////::::///////++++++++oo+++++oooooooosssyyyyysssyhdmdddhhhhyyssossyhddddhhhhhhhhhhhdd
++oshddmdddddddhyo+++osyyhysso+//////+oooooooo+++++////////////////////::::://///://::::/://+++//+++///+++////////+/://:::////////++//////////++ooooo+oosssyyyyysssyyhdddddhhhhyssossyhddddhhhhyyyyhhhdd
/+osyhdmddddddddhso++oosyhhyso++/////+oooooo+++++/++///////::::////://+/////+++/:://:/://://+++/////////++/://///++///////++++o+//++///:::::///++ooo++oosssyyyyyssssyhddmddhhhhyssossyhddddhhhhyyyyhhhdd
//+oshdmmddddddddyso++osyyhyyso+//////ooooooo+++++///+////:::::::///+/++osooooo+/////+///:////////::://://////+///++/+++++ooosso++////::::::://++ooo++oossyyyyyyysssyhdddddhhhhyssossyhddddhhhhyyyyhhhdd
//++syhdmmdddddddhyoo++osyhhysoo+/////osoooo++++++///++////::::::://+/+ossssosyyo++++++++////+////::////::/++++/+++oo++oosyyyhyso+///::::::::///+oo+++oossyyyyyyysssyhdddddhhhhyssossyhdddhhhhhyyyyhhhdd
+/++osyddmmdddddddhso++oosyhhyso++////ossooo+++++++++//////:::--::::/+oosssssssssssssosooo++++o++//+//++///+++++ssosysosyssyhyyyso++/::--:::///+ooo+ooossyyyyyyyyyssyhdddddhhhhyssossyhdddhhhhhyyyyyhhhd
+++++oshdmmmdddddddyso++osyyhhyso+////ossooo++o++++++//////:::----:/+oooo++++++++++ossssoooooossssssssssssssssssssosyssssssoooosoo++:----::://+ooo++oossyyyyssyyyyssyyhddddhhhhyssossyhdddhhhyyyyyyhhhdh
oo+++osyhdmmdddddddhyso++osyhhysso+//+ossssooooo++++///////::::----:/++//::::::///////////+++///////++++++++++++//+++++++++////+oo+/:---::://++oo+++ossyyyysssyyyyyyyhhddddhhhhyssossyhdddhhyyyyyyyyhhhh
oo++++osyddmmdddddddhyo++oosyhhyso+/+oosysssoooo+++++///////::::::::/+/:::::::::////:::::::::::-----::---::::::/:://////////:://+oo/::-:::///++++++oossyyyssssyyhhyyyhdddddhhhhyssossyhdddhhyyyyyyyyhhhh
soo++++oyhdmmddddddddyso++osyhhyysoossssssssooooooo++++//////::::::///::-:::::::///////:::::::::::::::::--::::::///////////:::://++++/:::///++++++oosyyyysssssyyhhyyyhdddddhhhhyssossyhdddhhyyyyyyhhhhhh
oooo+++osyhdmmdddddddhyso++osyhhysssyssosssssoooooo++++///+////::::::::--:-:::::////////:///::////::///:::://////////////:::::::::////::///+++++ooosyyyysoosssyyhyyyyhhdddddhhhyssossyhddhhhhyyhhhhhhhhh
oooo++++osyddmddddddddhso++ooyhhyyssyssossssssooooo++++++++++///::::--------:::://////::::::::://////////////////+///////:::::---::///://++++++ooossyyso++osssyyhyyyyyhhdddhhhhyssossyhddhhhhyyhhhhhhhhh
oooo+++++oyhddmddddhhhyso+++osyyysssyssoosssssssoooo++++++++++///:::---------:::::///::::::--:::::///:::::::::/:////////:::::-:----:////++++o+ooosyyso++++oossyyhyyyyyhddddhhhyyssossyhddhhhhyyhhhhhhhhh
++++++//++syhddddhysssssoo+++osssssssssooossssssssooo++++++++++//::--....-----:::::::::::::::::::://:::::-:::::::::::://::::-------:///++o+oooossyyso+//++oosssyhhyyyyhhhhhyyyyssoossyhddhhhhyyhhhhhhhhh
/////////+osyhddhysoo+ooso++++osssssooo++oosssssssssoo+++++++++++/::----------:---:::::---:::-:::-:::--:----:::::::::::::----------://++ooooosssyyso++++++oossyyyhyyyyhhhysssoooooossyhddhhhhyyyhhhhhhhh
//////////+osyhdhyssoosyyssooosssssoo+oo++oosssssssssooo+++++/+++/:------------------------::-::-----.------------:---------------:/+++ooooosssyyyso++++++oossyyyhyyyyhhyysoooooooossyhdddhhyyyyyyyyhhhh
://///////+osyhddhhyyyyhdhysssssoooo++oo++ooooosssyyyssoooo+++++++/:---------------------------------------------------------..---:++ooosssssyyhhhyo++++++oossyyhhyyyhhhhyyyssssooossyhdddhhyysssssyyyhh
::////////++osyhdddhhhhddhssssooooooo+oo++++ooooosssyyyssooo+++++++/::-:---.-------.---------------------::--------------.---.....-/oosssssyyyyhhhyso++++++ossyyyyyyyyyyhhhyyyyssoosyyhdddhhhyysssssyyhh
:::////+++++osyhdmddhhyyyssssooooooo+++o+++++oo++ooossyyyssooooooo+++/::-.......---------------------------------..--..-------..--:/osssyyyyhhhhhhyso++++++ossyyysssssssyyyhhyyyssssyyhddddhhyysssyyyhhh
:://++ooosoooosyddddyyssssssooooooooo+++o+++++++++++ossyyyysssssssso+/:--------.----.--------------:------------.-----...--------:+ossyyyyyyhhhhhyyso++++oossyyyssoooooosyhhhhyyssssyhhdddhhyyssssyyhhhh
::/+osyyyysooosyhhyysssssoooooooooooo+++o++++++++++++oosyyyyyssssssso/:---:-----..-..--------::----:---:--------.-----..---.---://+syyyyyyyhhhhdhysoooooosyyhhhyysssssssyhhhhhhyssssyhhdddhhyssoossyyhhh
::/+osyyysssoosssssssssoo++++ooooooo+o+++o+/+++++++++++ossyyyyyyyyssso//::::----.....------------------:-..--:--.---:-.--------:/ossyyyyyyyhhhhdmhysooo+oossyyyyyyyyyyyhhhhhhhhyysssyhhdddhhyyssssyyhhhh
/://+oosssoooooossoooooo++++++oooooooo++++++/+++++++++++oosyyyyyyyyyyso++//::------...---..---------::-----------.-::---:::::::/+osyyyyyyyhhhhdmmdyssooo++++++++oosyhhddddddddhhyysyyhhddddhhhhyyyhhhhhh
++/++oooooooosssso///+o++++++++oooooooo++++++//++++++++++oossyyyyyyyyysso+//:-::--:--.--:-..--------::-:::-::-------:--:::--::/ossyyyyyyyhhhhhmmmdhyssooooo++++++///+oshdddddddhhhyyhhddddddddhhhhhhdddd
soooooooooooooo+/:::/+++++++++++oooo+++++++++////+++++++++ooosssyssyssssss++///::::::--:-::-:----:--:::::------::::----:::::/+osyyyyyyyyhhhhhdmNmdhysssooo+++++++///////+syhhhddhhhhdddddddddddddddddddd
o++++++++++//:----:/+++++++++++++ooo++++++++++//:/++//+//++++oossssssssyyyso++//::::/:::-:::::-:/::-:::::---:--:::/::::////+osyyyyyyyyhyyhhhhdmmmddhssssooo++++++/////:::://++oosyyhhddmmmmmmdddddddmmmm
+++++++++/:-......-:/++++++++++++ooo+++++++++//////+++/////++++oossssssyyyyysoooo+////:::::--::::::///:::////////////++++ossyyyyyyyyyyyyhhhhhhddmdhhysssooo++++++//////:::::::::://++osyhdmmmmmmmmmmmmmm
oo++++/:-..........-/++++++//++++ooo+++++++++/////://+++//////+++oossssssyyyyyyysso+++/////::////+++++///++//+o++++oosssyyyyyyyyyyyyyyyhyyyhhhhdddhhyssssoooo+++++/////:::::::::::::::::/+oyydmmmmmmmNNN
++++/-..............:+++/++///+++ooo++++++++++///+/:://++//////++++oosssssyyyyyyyyyssssoooo+ooooooosooooooosoosssssyyyyyyyyyyyyyyyyyyyyyyyyhhyyhhhhyyssoooooo++++++////:::::::::////:::::::://+osyddmNNN
+/:-................-/+++//+///++oo++++++++++++//++//::/+////////+++oossssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhysosyyhyyssoooo+++++++++///+/////://////::::::::::::://+oydm
:-.................../++///////+++++++++++++++ooooso///:://///////+++ooosssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyso+ossyysssooo++++////////+ossoooooooo+///::::::::::::::::/o
..`..................:/+///////++++++++++++++oossooso//::://///////+++ooosssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhyyyyyyyyyyyyyyyyyyyyysyyyyyyso+++ossyssooo+++++/////////+sssoo++ooooo+////:::::::::::::--
......................:////////++++++++++++oooooosooso+//:::///////++++oooosssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssyyso//://oosssoo++++///////////+ossoo+++ooooooooo++++++///::::::
......`...............-////////+++++++++++ooosssosso+so+/:::::://+///++++oooossssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssyyyo+/:-::/ooyso++++/////::////:/+osooooooooooooooo+++++ooo+/////
....``.................:///////+++++++++ooooossooooso+so+//:::::://///++++oooossssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssyhys/::--::/+osso+++/////:::::/:::/+ooooooooooooooo+++++++ooo+++++
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ "How we doin'? - Jim Etheredge 2015"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>